// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sudokuBackEnd.DB.Data;

namespace sudokuBackEnd.Migrations
{
    [DbContext(typeof(SudokuContext))]
    [Migration("20210208164917_removeNextGameFromUser")]
    partial class removeNextGameFromUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("sudokuBackEnd.DB.Entity.GameEntering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("AvarageTime")
                        .HasColumnType("real");

                    b.Property<int>("DifficulitySettings")
                        .HasColumnType("int");

                    b.Property<string>("Entering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSuccessfullSolutions")
                        .HasColumnType("int");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameEntering");
                });

            modelBuilder.Entity("sudokuBackEnd.DB.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AuthId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Elo")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResolvedGamesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("sudokuBackEnd.DB.Entity.UserGameSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ResolvedGameEnteringId")
                        .HasColumnType("int");

                    b.Property<float>("Time")
                        .HasColumnType("real");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedGameEnteringId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGameSolution");
                });

            modelBuilder.Entity("sudokuBackEnd.DB.Entity.UserGameSolution", b =>
                {
                    b.HasOne("sudokuBackEnd.DB.Entity.GameEntering", "ResolvedGameEntering")
                        .WithMany()
                        .HasForeignKey("ResolvedGameEnteringId");

                    b.HasOne("sudokuBackEnd.DB.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ResolvedGameEntering");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
